# Generated by Django 2.2.7 on 2019-11-26 01:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="rato"),
            preserve_default=False,
        ),
    ]
