# Generated by Django 2.2.7 on 2019-12-07 22:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="Isso é um post legal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="keywords",
            field=models.CharField(
                default="privacidade,segurança,comunismo", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
