# Generated by Django 2.2.7 on 2019-12-09 00:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20191208_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="readtime",
            field=models.PositiveSmallIntegerField(default=13, editable=False),
            preserve_default=False,
        ),
    ]
