# Generated by Django 2.2.7 on 2019-12-10 01:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_readtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="has_code",
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
