# Generated by Django 3.0.1 on 2020-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_has_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lock_key',
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
