# Generated by Django 3.0.1 on 2020-02-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_lock_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lock_key',
            field=models.CharField(max_length=32),
        ),
    ]
